// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzczuecawsphsuagfakx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6Y3p1ZWNhd3NwaHN1YWdmYWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTAyNjEsImV4cCI6MjA3NDEyNjI2MX0.aHi78aIYnqlJG_GPKDQig3tXHURLO2XvELA4-KHZFLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});